### ISSUE TITLE
Publish data value with a historical timestamp? 

### ISSUE THREAD

**Issue by theschles** [adafruit/Adafruit_MQTT_Library#18]
Hi there,

I'm combining a Huzzah esp8266 with a HDC1008 and a photoresistor.

WiFi uses lots of battery so my hope was to be able to store on the esp8266 a series of data points with timestamps and then when the memory was running low or the chip's battery voltage appears to be dropping too low, publish the data points with their historical timestamps to Adafruit IO feeds.  

Publish() seems to only take one value.  Is there any way to do what I'm describing?

**Comment by andreavalle** [comment]
Maybe this?

for (n=0; n<datapoints; n++)
{
   Publish();
}

**Comment by theschles** [comment]
HI andreavalle,

Yeah I would use a for loop when I realized it was time to batch send the data (either memory almost full or battery running low).  The problem is that when I batch send the data to my data feed in Adafruit IO, Adafruit IO would interpret the data as happening at that very moment -- as opposed to when that data actually occurred.

I'd love it if there was an API for publish(value,time-stamp) or publish(value,negative-time-offset-in-seconds)

**Comment by andreavalle** [comment]
I see now.
Unfortunately I think the timestamp values associated with feed data are read-only.

**Comment by tapiralec** [comment]
AFAIK, the timestamps are generated server-side as data are received. Since this is the case, you might get a better response if you open an issue on [io-issues](https://github.com/adafruit/io-issues/issues), asking for submitting the timestamp as a feature request. I'm not sure if there are plans to implement it, however, because there are a lot of potential bugs involving inconsistent timestamping that would have to be dealt with.

As far as your particular problem goes, if you don't need to be able to visualize the data on Adafruit IO, a simple solution would be to concatenate your data and timestamp into a string, and publish that, then use python to grab the data at a later time and postprocess.

**Comment by jwcooper** [comment]
The plan is to add support for custom created_at timestamps from the REST API and from MQTT. This is fairly high on the list of things to do in order to begin supporting batch uploading of data.

**Comment by theschles** [comment]
Hi @jwcooper / @toddtreece / @tapiralec 

Per Alec's suggestion, I posted to adafruit/io-issues -- should I close this issue?  Should I close that issue?

**Comment by jwcooper** [comment]
We can close this issue and track using the io-issue.
