### ISSUE TITLE
Overzealous library dependencies

### ISSUE THREAD

**Issue by einglis** [adafruit/Adafruit_MQTT_Library#229]
I've been building a project for the Sonoff Basic (ESP8266) with the Arduino IDE for some time without issue.  Trying to transition to PlatformIO, I've been getting **conflicting declaration** errors like this one:

```
.pio/libdeps/sonoff_basic/WiFi101/src/bsp/include/nm_bsp.h:110:23: error: conflicting declaration 'typedef long unsigned int uint32'
  110 | typedef unsigned long uint32;
      |                       ^~~~~~
...
/home/edd/.platformio/packages/framework-arduinoespressif8266/tools/sdk/include/c_types.h:49:29: note: previous declaration as 'typedef unsigned int uint32'
   49 | typedef unsigned int        uint32;
      |                             ^~~~~~
```
By following the breadcrumbs, I found this issue: https://github.com/me-no-dev/ESPAsyncTCP/issues/172, which questions the compatibility of that library (which I'm also using) with this one, due to the WiFi101 dependency of the latter.

I tried locally editing the Adafruit MQTT `libraries.properties` file to remove _all_ the existing dependencies:
```
depends=Adafruit SleepyDog Library, Adafruit FONA Library, WiFi101
```
and that did the trick for me.  But that's not a sustainable solution because each new project will require the same local edit and that's a pain.

From what I can tell, **WiFi101** is only required by the FONA library, and _that_ is only required on FONA hardware.  On top of that, I'm pretty sure I read that **SleepyDog** does not work as expected on the ESP8266.

I wonder if there is a way to split the dependencies so that only FONA targets depend on the FONA (and SleepyDog?) libraries?  Of course, my primary issue is the WiFi101 dependency; I wonder whether removing this will break examples?

Time permitting, I'll give some of these modifications further investigation, but would value a more experienced opinion.

**Comment by tyeth** [comment]
Not related to Wifi101 usage, but as far as ignoring conflicting dependencies in platformIO goes, you can add a line to ignore certain libraries for certain environments which may be you're easiest/quickest win. For example we declare a bunch of libraries for all environments, then ignore depending on architecture / conflicts (we also adjust lib_ldf_mode and lib_compat_mode): 
https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/platformio.ini#L78

On the fixing this library front, we can specify architectural dependencies for platformio in a new library.json file. They suggest having a section like this: https://docs.platformio.org/en/latest/manifests/library-json/fields/dependencies.html#dependencies
```json
"dependencies":
[
    {
        "owner": "bblanchon",
        "name": "ArduinoJson",
        "version": "^6.16.1"
    },
    {
        "owner": "me-no-dev",
        "name": "AsyncTCP",
        "version": "*",
        "platforms": ["espressif32"]
    },
    {
        "name": "external-repo",
        "version": "https://github.com/user/package.git#1.2.3"
    },
    {
        "name": "external-zip",
        "version": "https://github.com/me-no-dev/AsyncTCP/archive/master.zip"
    }
]
```
The tricky bit is the FONA hardware is a shield, and the WINC1500 comes as both feather and shield/breakout, so there's no clear architecture to rule out without affecting users who may truly depend on the functionality. There is a very small chance that it may be acceptable to consider the FONA hardware + software as obsolete (due to sunsetting 2G networks in different countries), but the WINC1500 is still for sale so it feels wrong to cut out those users.

We could do a major version release and break compatibility, removing FONA, sleepydog and winc1500 dependencies (wifi101), instead adding comments to the header section of the relevant examples to instruct users to manually install them (also the readme).

Tagging @brentru to get another perspective

**Comment by brentru** [comment]
@einglis 

> I'm pretty sure I read that SleepyDog does not work as expected on the ESP8266.

SleepyDog _does_ work on ESP8266. However, its behavior is not identical to SleepyDog on other ESPx platforms since ESP8266's watchdog timer WDT is pre-determined by software and not set-able.

> I wonder if there is a way to split the dependencies so that only FONA targets depend on the FONA (and SleepyDog?) libraries? ... WiFi101 is only required by the FONA library, and that is only required on FONA hardware.

As Tyeth mentioned, FONA is a shield that can be added to different products. So adding specific architectures to the library.properties file for the FONA library wouldn't be accurate, as it _can_ run on those architectures. 

Looking at your compiler's output, it looks like WiFi101 is part of the Sonoff board support package, too, causing the conflicts:
`/sonoff_basic/WiFi101/src/bsp/include/nm_bsp.h:110:23`

**Comment by einglis** [comment]
Thanks @tyeth and @brentru for your input.  It's really helpful to get some extra context; it does seem like removing these dependencies would cause needless pain elsewhere.

Frustratingly, I've just tried to reproduce my compilation issues so I could explore the `lib_ignore` suggestion, and there is no sign of the original conflicting declarations  :angry:   Oh well, I suppose I should be happy that it's working...

I'm happy for you to close this ticket if you wish.  Thanks again for your time.
