### ISSUE TITLE
Duplicate messages received by Adafruit MQTT Library and ESP8266

### ISSUE THREAD

**Issue by ghutib** [adafruit/Adafruit_MQTT_Library#7]
I'm using the ESP8266 with the Arduino IDE and this Adafruit MQTT Library and receiving duplicate messages.

After subscribing to a topic and receiving the first correct message, the MQTT library then receives extra messages which are duplicates of the first real message. The last time I tested there were 6 duplicates over a 45 minute period.

THE MQTT sub loop is from the Adafruit example code in mqtt_esp8266.ino:

// this is our 'wait for incoming subscription packets' busy subloop
Adafruit_MQTT_Subscribe *subscription;
while ((subscription = mqtt.readSubscription(1000))) {
   if (subscription == &onoffbutton) {
      Serial.print(F("Got: "));
      Serial.println((char *)onoffbutton.lastread);
    }
}

I tried this same test with three different MQTT brokers (test.mosquitto.org, cloudmqtt.com, and my own server running Ponte), and the problem appears with each of the brokers.

I tried two other MQTT clients (nodemcu and Debian mosquitto_sub) against the cloudmqtt.com and ponte brokers, and the problem does NOT appear.

**Comment by tdicola** [comment]
Hrm I can't repro this with the mosquitto test server (http://test.mosquitto.org/).  Here's the auth configuration I was using for the sketch:
```
/************************* Adafruit.io Setup *********************************/

#define AIO_SERVER      "test.mosquitto.org"
#define AIO_SERVERPORT  1883
#define AIO_USERNAME    ""
#define AIO_KEY         ""
```
And the feed config (slight change to add my name/a unique value to the front of the feed so nothing conflicts with it on the test server):
```

// Setup a feed called 'photocell' for publishing.
// Notice MQTT paths for AIO follow the form: <username>/feeds/<feedname>
const char PHOTOCELL_FEED[] PROGMEM = AIO_USERNAME "tdicola/feeds/photocell";
Adafruit_MQTT_Publish photocell = Adafruit_MQTT_Publish(&mqtt, PHOTOCELL_FEED);

// Setup a feed called 'onoff' for subscribing to changes.
const char ONOFF_FEED[] PROGMEM = AIO_USERNAME "tdicola/feeds/onoff";
Adafruit_MQTT_Subscribe onoffbutton = Adafruit_MQTT_Subscribe(&mqtt, ONOFF_FEED);
```
I let it connect to the mosquitto test server, then using this Paho MQTT python library (https://pypi.python.org/pypi/paho-mqtt) code on another machine I published a message to the 'tdicola/feeds/onoff' feed that the sketch is listening to.  Here's the code I was using:
```
import paho.mqtt.publish as publish
publish.single('tdicola/feeds/onoff', payload='ON', hostname='test.mosquitto.org', port=1883)
print 'Sent message!'
```
In the serial output I only see one message received:
```
Sending photocell val 249...OK!
Got: ON

Sending photocell val 250...OK!
```

I'm curious how are you publishing messages when testing on other brokers--could it be sending two messages?

For Adafruit IO specifically though it does look like right now one change, like pressing a toggle switch on a dashboard, can generate two events. It's something being looked at to simplify and only generate one message, but for now there could be duplicates since it's QOS 0.

For other brokers though if you send one message and receive two responses with the library it does seem unexpected.  Let me know if you have more details on a repro example and I can try it too.  Thanks!

**Comment by toddtreece** [comment]
the duplicate message issue was fixed with io.adafruit.com, so i'm going to close this one
